[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/health"
restartPolicyType = "on_failure"

[service]
startCommand = "npx prisma db push --schema=prisma/schema.prisma && node dist/index.js"
